server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 7489102883
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PATIENT-SERVICE
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

